[package]
name = "imap2slack"
version = "0.1.0"
authors = ["nn <nn@nn.nn>"]

[dependencies]
imap = "*"
openssl = "*"
regex = "*"
quoted_printable = "*"
slack-hook = "*"
url = "*"
toml = "*"
serde = "*"
serde_derive = "*"
lazy_static = "*"